### ISSUE TITLE
ImportError: cannot import name '_solver' from 'swmm.toolkit'

### ISSUE THREAD

**Issue by kokodayour** [Zhiyu014/GNN-UDS#2]
Whether I am using the Python 37 virtual environment or the Conda virtual environment, it has reported this error. 
I once referred to the discussion of the Pyswmm library(https://github.com/pyswmm/pyswmm/discussions/323), the underlying libraries that this project relies on, there was similar problem in 2021. 
It once said that this issue would be resolved in the next version, and I have reviewed the source code. The author did make modifications, but I still encountered a similar problem

**Comment by Zhiyu014** [comment]
Hi! I assume it is a pyswmm and swmm-toolkit compatibility problem, as pyswmm cannot find its dependency swmm-toolkit in conda envs due to directory problems.
May be you could refer to the [compatibility table by pyswmm](https://github.com/pyswmm/pyswmm?tab=readme-ov-file#swmm-and-python-compatibility-table) and upgrade your swmm-toolkit to corresponding version.

**Comment by kokodayour** [comment]
The environment can now be installed normally and thank you very much for your help!




北冥有鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zhiyu014/GNN-UDS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月27日(星期五) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Zhiyu014/GNN-UDS] ImportError: cannot import name '_solver' from 'swmm.toolkit' (Issue #2)





 
Hi! I assume it is a pyswmm and swmm-toolkit compatibility problem, as pyswmm cannot find its dependency swmm-toolkit in conda envs due to directory problems.
 May be you could refer to the compatibility table by pyswmm and upgrade your swmm-toolkit to corresponding version.
